### PR TITLE
Changed ".size()" to ".length"

### PR DESCRIPTION
**Pull request by UltraFireFX**
You cannot invoke size() on array type Player[]

### CODE REVIEW

**Comment by UltraFireFX** [comment]
@Hidendra Please change this.
```.length``` can only be cast on strings and returns characters in the string; ```.size()``` can be cast on arrays and returns the count of elements in the array

**Comment by Hidendra** [comment]
@UltraFireFX You're right, but `getOnlinePlayers` [returns a collection](https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/Server.java#L127), not an array.

CraftBukkit provides backwards compatibility, so `.length` appears to work, but Spigot removes that. Plugin-Metrics here uses the 1.7.10 API, so if you want to support older versions you'll need to include a copy of the Metrics class you want directly into your plugin (keep in mind using .length won't work on Spigot if you want to support that.)

**Comment by UltraFireFX** [comment]
Couldn't there be a way to check if the server is running *CraftBukkit* or *Spigot* and use ```.length``` or ```.size``` respectively?

**Comment by Yannici** [comment]
You can check whether _craftbukkit_ or _spigot_ is running by checking if **org.spigotmc** package is loaded / available. But I think it's stupid to use `.length` as long the return type of `getOnlinePlayers` is a collection.

**Comment by UltraFireFX** [comment]
``.size`` and ``.length`` wouldn't throw an exception if used incorrectly like above, would they? Otherwise we could use try-catch brackets and go from there.

**Comment by lorenzop** [comment]
here's how I handled this problem. just check the return type of the getOnlinePlayers() function and use .size or .length as needed.

	// Bukkit.getOnlinePlayers() changed the api from returning an array to a Collection in 1.7.10 and broke backward compatibility
	public static Player[] getOnlinePlayers() {
		try {
			if(Bukkit.class.getMethod("getOnlinePlayers", new Class<?>[0]).getReturnType() == Collection.class)
				return ((Collection<?>) Bukkit.class.getMethod("getOnlinePlayers", new Class<?>[0]).invoke(null, new Object[0])).toArray(new Player[0]);
			else
				return ((Player[])Bukkit.class.getMethod("getOnlinePlayers", new Class<?>[0]).invoke(null, new Object[0]));
		} catch (NoSuchMethodException e) {
			e.printStackTrace();
		} catch (InvocationTargetException e){
			e.printStackTrace();
		} catch (IllegalAccessException e){
			e.printStackTrace();
		}
		return null;
	}

**Comment by Hidendra** [comment]
If you want to PR that I'd be happy to pull :) otherwise will be a few days before I look myself

**Comment by Yannici** [comment]
Careful, its not `Bukkit.class` but `Server.class`. I just created a new pull request #66

**Comment by Hidendra** [comment]
Closing this as it was covered by #66.

**Pull request closed without merging**
