### PR TITLE
Organized

### PR DESCRIPTION
**Pull request by nerdtron123**

### CODE REVIEW

**Comment by Nicewuerfel** [comment]
Why would you do that? It's good practice to surround one-line-statements with curly braces.

**Comment by sgdc3** [comment]
Yeah, i agree ;)

**Comment by sgdc3** [comment]
This PR and the other old ones should be closed

**Comment by Hidendra** [comment]
I agree. I'll go through them once I'm at my laptop.

**Comment by sgdc3** [comment]
@Hidendra You should also check all the open issues from 2013 and 2014 xD

**Pull request closed without merging**
